" No audible bell
set vb

" No toolbar
set guioptions-=T
set guioptions-=m
set guioptions-=r

" Use console dialogs
set guioptions+=c

colorscheme Darkside
set novisualbell
set guifont=Source\ Code\ Pro
