#ZSH_THEME="robbyrussel"

COMPLETION_WAITING_DOTS="true"

export LANG=en_US.UTF-8
export PATH="$PATH:/home/lubiana/.config/composer/vendor/bin"
export VISUAL="nvim"

# Customize to your needs...
#TERM=xterm

# stolen from:
# https://twitter.com/chris__martin/status/420992421673988096
alias such=git
alias very=git
alias much=git
alias wow='git status' 
alias yolo='git commit -am "DEAL WITH IT" && git push -f origin master'
alias vim='nvim'

# stolen from:
# https://twitter.com/hanshuebner/status/319910203346808832
alias doch='sudo $(fc -ln -1)'
. /etc/profile.d/vte.sh

