ZSH_THEME="evan"

COMPLETION_WAITING_DOTS="true"

export LANG=en_US.UTF-8

# Customize to your needs...
TERM=xterm

alias such=git
alias very=git
alias much=git
alias wow='git status' 
alias yolo='git commit -am "DEAL WITH IT" && git push -f origin master'
alias wgetr='wget --no-check-certificate -r --no-parent --reject "index.html*"'
alias ssocks='export SOCKS_SERVER=127.0.0.1:1234'
alias v="vim --servername remote --remote-tab"
alias vv="vim --servername remote"
alias gv="gvim --servername remote"
alias doch='sudo $(fc -ln -1)'
alias ttmux='tmux -2 a || tmux -2'
alias composer="sudo docker run --rm -i -t -v \$PWD:/srv composer"
alias php-dev="sudo docker run -i -t -P -v \$PWD:/srv php"
